# examples/run_compiler.py

import json
from plexus_core import build_ast_from_json
import os

# Define file paths relative to this script
INPUT_FILE = "input_graph.json"
SUB_DIRECTORY = "files_generated"
OUTPUT_FILE = "generated_script.py"
CURRENT_DIR = os.path.dirname(__file__)


def main():
    """Reads a JSON graph, compiles it, and saves the Python script."""
    print(f"--- Running Plexus Compiler ---")

    # Read the input JSON graph
    input_path = os.path.join(CURRENT_DIR, INPUT_FILE)
    print(f"Reading JSON graph from: {input_path}")
    with open(input_path, 'r') as f:
        graph = json.load(f)

    # Build the Python code from the graph
    python_code = build_ast_from_json(graph)

    # Save the generated code to a file
    if not os.path.exists(os.path.join(CURRENT_DIR, SUB_DIRECTORY)):
        os.makedirs(os.path.join(CURRENT_DIR, SUB_DIRECTORY))
        print(f"Creating directory: {SUB_DIRECTORY}")
    else:
        print(f"Directory {SUB_DIRECTORY} already exists.")
    output_path = os.path.join(CURRENT_DIR, SUB_DIRECTORY, OUTPUT_FILE)
    print(f"Saving generated Python script to: {output_path}")
    with open(output_path, 'w') as f:
        f.write("# Auto-generated by Plexus Compiler\n\n")
        f.write(python_code)

    print("\nCompilation complete!")
    print(f"Run 'python {OUTPUT_FILE}' to execute the generated code.")


if __name__ == "__main__":
    main()
